### ISSUE TITLE
undefined reference when compile

### ISSUE THREAD

**Issue by pzy2253999075** [andreanobile/opencv_ffmpeg_streaming#4]
Hi @andreanobile ,I am interested in this work。but when I try compile the code，some errors occurs below：
 
![image](https://user-images.githubusercontent.com/15712923/65657524-5b97e000-e056-11e9-8d77-4b973ccf129d.png)
I guess that‘s because of the ffmpeg version. I have installed the ffmpeg of newest version. Could you tell me which ffmpeg version do you use when compiling code or the real reasons for this error if you know，thanks!

**Comment by andreanobile** [comment]
Hi, I use ubuntu 18.04. Try check if you have libavcodec-dev installed.
Andrea

**Comment by pzy2253999075** [comment]
Hi @andreanobile,sorry for my late . I have installed libavcodec-dev in ubuntu16.04 and I also installed n4.2dev version ffmpeg from git source，now new error occurs below：
![image](https://user-images.githubusercontent.com/15712923/65824992-fd603c80-e2a3-11e9-8317-aaf1eff6e6e3.png)
I follow some solutions on google like add option -lavcodec-ffmpeg after gcc，but still can‘t solve my problem and I've been confused by it for  2 days，Do you kown how to fix this? Thanks.

**Comment by pzy2253999075** [comment]
Hi @andreanobile ，I've solved the compilation problem (by adjusting the order of dynamic link libraries).But now I want to improve the streaming code.In a good network situation, I can stream my video well，but I can not guarantee that the network will always be good.I hope that when the network is bad, even disconnect for a period of time, the streaming process can resume and continue to push when network recover. I have tried, when I was streaming the video, I manually disconnected the network, the streamer stopped quickly. After 20 seconds, I resumed the network, the process resumed to stream as well  in a few seconds.But if I disconnect the network for five minutes or longer, when the network is restored, the  process blocked.Do  you know how to resume the streamer instread of blocking  no matter how long the network is disconnected but  eventually recovered（not by restarting the program）.Could you give me some solution if you know ，thanks again.

**Comment by andreanobile** [comment]
HI, good that you solved the compilation, if the network goes down for 5 minutes maybe the problem is in the network as 5 minutes is a very long time. you could try to detect the network failed with another program and restart the streamer if detect network failure for too long.
