### ISSUE TITLE
Stream Opencv frames to rtmp in python

### ISSUE THREAD

**Issue by amansaini25** [andreanobile/opencv_ffmpeg_streaming#6]
Hi Andrea,

I'm looking for something like this project, in which we can stream frames after processing in OpenCV to some RTMP URL. I can't understand how to use this repo in my project.
Please help me with this!

**Comment by andreanobile** [comment]
Hi CRAZYMONTY,
i have put a readme in the python folder.

**Comment by beyond21299** [comment]
I didn't get an error from cmake,also no error from make. But I don't konw hwot to use this by python.
![微信截图_20210107150129](https://user-images.githubusercontent.com/18564312/103862033-4f278180-50f9-11eb-8dac-718c2bf79401.png)
![微信截图_20210107150152](https://user-images.githubusercontent.com/18564312/103862037-5189db80-50f9-11eb-8e71-1ecd9e8e5334.png)

**Comment by beyond21299** [comment]
> I didn't get an error from cmake,also no error from make. But I don't konw hwot to use this by python.

The examples given in the project also work.Can you teach me how to use this by python

**Comment by beyond21299** [comment]
> Hi Andrea,
> 
> I'm looking for something like this project, in which we can stream frames after processing in OpenCV to some RTMP URL. I can't understand how to use this repo in my project.
> Please help me with this!

I didn't get an error from cmake,also no error from make.
The examples given in the project also work.But I don't konw hwot to use this by python. Can you teach me how to use this by python?
